### ISSUE TITLE
fiduswriter with docker ?

### ISSUE THREAD

**Issue by reyman** [fiduswriter/fiduswriter#114]
Is there some plan actually to create a docker container to make an easy install/update/upgrade for self-hosted fiduswriter ?

**Comment by johanneswilm** [comment]
There is no plan, but you are welcome to help with that.

**Comment by rhunwicks** [comment]
If I create a Dockerfile, are you interested in a PR?  If so, please can you reopen this issue?

Also, if I do create a Dockerfile, what version of Python do you prefer? We are using 3.5 with our Django 1.9 apps, but I don't know if the rest of the Fiduswriter code will work with 3.4+, or whether I should stick with 2.7.

**Comment by johanneswilm** [comment]
Sure, but our priority will be the standard manual install on Ubuntu. In other projects I have noticed how things became ever more complex when they tried to adjust things to work with Docker until in the end it was impossible to install manually. So if you can do it without that happening, such a PR would be accepted.

It has been a while since I last tried running it on Python 3. At that time it still had some dependency issues. This may be less of an issue now, but there are likely some adjustments that still have to be made.

**Comment by moritzfl** [comment]
I created a docker image for fiduswriter because I wanted to try it out as alternative to sharelatex.
Perhaps you would like to take a look at: https://hub.docker.com/r/moritzf/fiduswriter/

**Comment by johanneswilm** [comment]
@moritzfl That is very cool! I am fairly unfamiliar with the specifics of docker. So some questions for you:

- I see that you included some instructions to manually modify the "allowed hosts". Is this usually how it's done with docker images? Or would this usually be handled by some kind of install/setup script?

- What happens when we release a new version? Do we/you need to update the image?

**Comment by moritzfl** [comment]
**Configuration**
The "Docker-way" would be to allowed hosts etc. via [environment variables](https://docs.docker.com/engine/reference/run/#env-environment-variables). Generating an configuration.py-file with a given set of environment variables would theoretically be possible but the logic for that ofc always needs to be in sync with the according file-definition that fiduswriter (could cause issues if that is not the case and would mean development overhead).

In general, projects handle this very differently:
1. [Gogs](https://github.com/gogits/gogs/blob/master/conf/app.ini) does store those things in a configuration file (similar to fiduswriter). They have a custom config file on top for user modification but afaik do  not allow to define settings via environment variables. They do however have a setup dialog on the first start that allows to define the most important settings - for any changes after that point in time you will still have to create/modify app.ini

2. [ShareLaTeX](https://github.com/gogits/gogs/blob/master/conf/app.ini) uses environment variables to configure almost everything. Those variables are listed underneath "environment:" [here](https://github.com/sharelatex/sharelatex/blob/master/docker-compose.yml)

_My take on this: I do not consider the configuration with environments variables necessary. It is nice to have but if as little "docker induced friction" with the project as possible is a goal, I think the solution to have the configuration file is quite neat. After all it is still possible to map all relevant data to one directory (the /data directory) you should be able to persist the important data and settings when upgrading the docker-container or even moving your installation to a new machine._

**What happens if a new version of fiduswriter is released?**
As long as the general setup process does not change for fiduswriter in general, only slight modifications on the dockerfile are needed. Theoretically the only requirement as of now would be to change "VERSION: 3.1.0" to reflect the current version in the dockerfile and trigger a build on dockerhub => Basically a 2min process. After that you just need to sit back and wait for the build process to finish on docker hub.
Additionally it is possible to create "latest" and "develop" dockerfiles that always pull the latest release or the current state of the repository. Those can be triggered as [automated builds](https://docs.docker.com/docker-hub/github/) on [dockerhub](https://docs.docker.com/docker-hub/builds/#remote-build-triggers).

**Comment by johanneswilm** [comment]
@moritzfl Hey, thanks for explaining all this. We just released a version 3.2.0 of Fidus Writer. What should we do now to get a docker version of that? Also, @sadeghiafshin suggested we should link to it from our github readme file. What do you think about that?

**Comment by sadeghiafshin** [comment]
Yes, it will help people to reach it when it gets uploaded somewhere like here: https://hub.docker.com and then Johannes can link to it.

**Comment by johanneswilm** [comment]
@sadeghiafshin Apparently it exists there already: https://hub.docker.com/r/moritzf/fiduswriter/

**Comment by sadeghiafshin** [comment]
@johanneswilm it is pushed 2 days ago, so can be the last version. then we just need to refer to it.

**Comment by johanneswilm** [comment]
@sadeghiafshin Yepp, you're right: https://hub.docker.com/r/moritzf/fiduswriter/tags/

Ok, so we should make a link to it.

**Comment by moritzfl** [comment]
@johanneswilm Just to shed some light on how I currently manage the docker builds:
I receive a mail notification every time  a fiduswriter release is published so when a release happens there should only be a short delay (maybe a couple of days tops) until I get around to publish a docker-build. I do this manually atm but as the effort related to the task is minimal, the manual process does not bother me very much. If you are ok with this procedure I do not mind taking care of the task of keeping the docker-releases in sync with the fiduswriter project. As stated before, completely automated builds triggered directly from the fiduswriter-repo would also be possible but would also require additional configuration (web hooks etc. - my prior experience in that matter is mainly with in-house automation of builds but DockerHub and GitHub seem to offer sufficient functionality). Just let me know what you think and I'll either continue to proceed as before or further explore the automation options :P (I currently have to prep for exams so I might not do that directly). 

As for linking to the GitHub/Docker-Sites you are of course welcome to do so if you think it offers a benefit to the users.

**Comment by johanneswilm** [comment]
@moritzfl You doing that would be of great help! So yes, thank you very much. It would be good if you could notify me if you get tired of doing this some time in the future. If you don't notify me, I'll probably first learn about it when someone else complains.

Is there some special badge you would want me to use to link to that docker site, or should I just add a textual link in the readme file?

**Comment by moritzfl** [comment]
@johanneswilm sounds good to me - I'll continue with manual builds for now and let you know if I intend to drop out and help transitioning the task to someone else if needed.

You can include the link in any form you like - no special badge needed :)
