### ISSUE TITLE
LanguageTool skips most part of document

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter#1200]
On a custom snap installation of FW with installed LanguageTool (LT), LT only checks a small part of a given document. For this part, LT underlines suspect words and suggests correct alternatives, but the most part of the document obviously remains unchecked. At least, no words are underlined. This does not happen to all documents, but to many of them.

This behaviour is not connected to a specific document template, nor to the presence/absence of abstract or keywords. Any suggestions where to look for possible reasons are welcome!

**Comment by johanneswilm** [comment]
@nmueller18 I need more information in order to investigate. What do the documents where this happens have in common? Do they contain something specific (such as a table or something)? Maybe they are lagrer than other documents? Is it only the beginning of the document that is being checked when that happens? Would it be possible to create a test document in which  this happens and forward to me?

**Comment by nmueller18** [comment]
Somehow, it seems related to length because if I cut enough words in one of the offending documents, the underlining suddenly appears (though in wrong places). However, in another document of about the same length, LT works without problems. Obviously, LT is choking on something in the problematic document. I send you two lengthy documents, one with and the other without working LT.

**Comment by johanneswilm** [comment]
@nmueller18 This issue should be fixed in version 3.10.18 which was released today. The problem was that sometimes the spell checking of a specific section took more than 20 seconds. The limit has now been increased to 88 seconds. Firefox has a hard limit of 90 seconds waiting for responses from servers, so if the new limit is still not enough, we may have to resort to other ways of getting around the limit.

Please reopen this ticket if it turns out that the issue has not been resolved fully.
