### ISSUE TITLE
customise signup email

### ISSUE THREAD

**Issue by zeigerpuppy** [fiduswriter/fiduswriter#174]
How does one set the site_domain variable?
Currently, emails say they are coming from "example.com"

**Comment by johanneswilm** [comment]
Sorry, also this is not a bug. Check out the standard documentation that comes with the various packages that make up Fidus Writer. Or hire my services for said amount.

**Comment by johanneswilm** [comment]
And please stop opening new issues unless you are willing to pay for the 5-10 minutes it takes me to answer and close them.

**Comment by zeigerpuppy** [comment]
Some more specific docs on configuration would be helpful for new users I think.
I am happy to amend the docs in the wiki here, but not sure if that's the right place to put things like this.
Is there a doc somewhere I've missed?

**Comment by johanneswilm** [comment]
Well see. None of this is difficult to find out if you know the packages involved. And I get that for you it's would be nice if I could just spend an hour to give you this information for free. The problem is that if I help ten people like you one hour for free per day, I end up working constantly with no food on the table. That's why, unfortunately, I have to limit the support to issues that are directly bugs in the software for people who don't contribute to Fidus Writer.

This shouldn't be difficult for you to figure out. With a little creativity + Google and looking at what is inside of Fidus Writer, you should be able to figure this out.

**Comment by johanneswilm** [comment]
@zeigerpuppy thanks for the last two bug reports. They were actually helpful. The domain variable, and most other config options that are not specific to Fidus Writer are django config options. So you can look it up in the various django manuals.

However, note that Fidus Writer replaces the ```./manage.py runserver``` command of Django with its own. Fidus Writer bundles the Tornado webserver for this and uses websocket connections on the editor page. This will make normal proxying impossible, but there are several tutorials out there on how to set tornado up behind an nginx server. I haven't checked lately if there is now something similar for apache.

**Comment by almereyda** [comment]
For people who come return here after me, the example.com messages stem from the `django-allauth` package.

References:

- https://stackoverflow.com/questions/51886614/django-rest-auth-reset-password-email-contains-example-com-domain-instead-of
- https://stackoverflow.com/questions/11372064/django-registration-how-do-i-change-example-com-in-the-email
