### ISSUE TITLE
unusual call to URL: testp4.pospr.waw.pl

### ISSUE THREAD

**Issue by zeigerpuppy** [fiduswriter/fiduswriter#178]
I noticed this in the logging:

```
Invalid HTTP_HOST header: 'testp4.pospr.waw.pl'. You may need to add u'testp4.pospr.waw.pl' to ALLOWED_HOSTS.
Report at http://testp4.pospr.waw.pl/testproxy.php
Invalid HTTP_HOST header: 'testp4.pospr.waw.pl'. You may need to add u'testp4.pospr.waw.pl' to ALLOWED_HOSTS.

Request Method: GET
Request URL: http://testp4.pospr.waw.pl/http:/testp4.pospr.waw.pl/testproxy.php
Django Version: 1.9.5
Python Executable: /opt/fiduswriter/venv/bin/python
Python Version: 2.7.6
Python Path: ['/opt/fiduswriter', '/opt/fiduswriter/venv/lib/python2.7', '/opt/fiduswriter/venv/lib/python2.7/plat-x86_64-linux-gnu', '/opt/fiduswriter/venv/lib/python2.7/lib-tk', '/opt/fiduswriter/venv/lib/python2.7/lib-old', '/opt/fiduswriter/venv/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/opt/fiduswriter/venv/local/lib/python2.7/site-packages', '/opt/fiduswriter/venv/lib/python2.7/site-packages']
```

I assume there shouldn't be a call to this URL, perhaps it's left over from internal testing?

**Comment by johanneswilm** [comment]
What this message says is that your server is receiving a request for http://testp4.pospr.waw.pl/testproxy.php, but given that testp4.pospr.waw.pl isnot in its list of acccepted hostnames, it throws this error rather than trying to serve the file.

This is not in the sourcecode of Fidus Writer. This is people trying to see if they can hack your server.

This address is fairly common for that. A simple google search can show you this: https://www.google.com.py/#safe=off&q=testp4.pospr.waw.pl

**Comment by zeigerpuppy** [comment]
Thanks, that's helpful to know.
