### ISSUE TITLE
URI identification - through unique marking functionality 

### ISSUE THREAD

**Issue by sadeghiafshin** [fiduswriter/fiduswriter#442]

**Comment by s6fikass** [comment]
@sadeghiafshin 

an example of the URI used
http://localhost:8000/document/4/?anchor=anchor3870770450

example of the outlines or anchors summary

![image](https://user-images.githubusercontent.com/19859475/27469483-0bcabf02-57f0-11e7-849a-da77c5f8ed7b.png)

**Comment by johanneswilm** [comment]
Good start! For a quick demo, this is OK. If we want to merge it, we still need  need to take care of a few more things:

* The code was copied from the comment code, which is fine. But make sure to remove all those parts not relevant to anchors and change comments/function names to refer to "anchors" not "comments", otherwise this quickly turns into unmaintainable spaghetti code.

* There needs to be an interface that at least allows:
    * addition of anchor
    * removal of anchor
    * change of anchor text

* The anchors need to be their own mark type in the schema. Do not just use the mark type of comments.

* Add a way to link to anchors from the link dialog.

* Add the anchors to the export filter:
    * latex
    * word
    * odt
    * epub
    * html

* Upgrade the file version number so that you don't accidentally export from an instance with this feature to an older version without this feature. Add corresponding upgrade filters.

In total, I would calculate that the remaining items will account for around 95% of the programming time on this. So if 2 hours were spent on programming what we currently have, around 38 more hours will need to be invested into the remaining parts.

**Comment by sadeghiafshin** [comment]
@s6fikass I have check it out here> 
https://fiduswriter-devel.gesis.org/document/1/
it does not work by me. Can you explain what steps should be done to make it work after checking out the code.

**Comment by s6fikass** [comment]
@sadeghiafshin 
1. You insert an anchor from the button next to the insert comment button
2. After you insert an anchor  you can check it in the outlines section
3. There you find the URI and that URI scrolls to that anchor

**Comment by sadeghiafshin** [comment]
@s6fikass  .
Please perform them one by one and note here when one of them is done.

- The addition of anchor could be done with the same button. It just needs to update its icon.
- Removal of anchor could be done by a close sign over the tagging URI.
- Over the tagging URI we need "copy to memory" button as well. 
- When the window of tagging URIs is hidden all the highlighted texted by tags should not be shown.
- When URI of a tagged part is given in browser only that part of the text should stay highlighted.

**Comment by s6fikass** [comment]
@sadeghiafshin 

- [done] The addition of anchor could be done with the same button. It just needs to update its icon.
- [done] Removal of anchor could be done by a close sign over the tagging URI.
- [done] Over the tagging URI we need "copy to memory" button as well.
- [done] When the window of tagging URIs is hidden all the highlighted texted by tags should not be shown.
- [done] When URI of a tagged part is given in browser only that part of the text should stay highlighted.

committed in: [4d627f1](https://github.com/fiduswriter/fiduswriter/commit/4d627f18046b9770349872c3ee207678b3f0b0da)

**Comment by sadeghiafshin** [comment]
good work till now, I added it to the test system and we tested it together on the dev system here  https://fiduswriter-devel.gesis.org/document/1/

the debugging feedbacks:
1. when the anchor is used to open the document when the outline button is pressed to show the link the highlight is removed.

2. the multi line highlights are converted to several anchors. 

@s6fikass your next task will be debugging.

**Comment by sadeghiafshin** [comment]
also please check out the last version of FW, and add to it with the new PM and see if does not have any conflict.

**Comment by s6fikass** [comment]
@sadeghiafshin 

1. when the anchor is used to open the document when the outline button is pressed to show the link the highlight is removed.(done)
2. the multi line highlights are converted to several anchors.(done)

[commit](https://github.com/fiduswriter/fiduswriter/commit/199254c19ecd4c905a1b851cf725b1b8c92f66d1)

**Comment by sadeghiafshin** [comment]
Hi @s6fikass , just tested , the pythion manage.py tranpile gives error. Please check it below:

document.js: Unexpected token (262:2)
  260 | }
  261 |
> 262 | <<<<<<< HEAD
      |   ^
  263 | class AnchorMark extends MarkType {
  264 |     get attrs() {
  265 |         return {

**Comment by s6fikass** [comment]
we tested it and solved the issue

**Comment by johanneswilm** [comment]
Hey,
I have now checked out the fidus_URI branch. Great work! A few minor things:

* Try to update to recent version of Fidus Writer. This one this is based on was forked from on May 20th, before we merged Niloofar's IDs for headlines and alter figures. More recently the upgrade to the recent prosemirror has made quite a difference as well. 

* There are some things here that have the same functionality as what is present in head, it is just done in a different way. For example links to a headline is simply using the hash at the end of the url and is using an argument in the case of this. When You upgrade this to a recent version of Fidus Writer, it would be good to expand upon and plug into the existing functionality rather than have two separate ways of doing the same thing.

* The box on the side works with very short documents, but it seems like it will be a problem with 15 page long documents where the user needs to scroll up and down all the time. I just finished a decoration plugin for external and internal links that are then "inline" and only show when the selection is inside the given link [1]. Maybe something similar this would be a solution that could be made to work for this?

* I noticed some smaller issues (active anchor doesn't go away if I delete the corresponding anchor, etc.), but it would probably be better to just wait with this until it has been upgraded to newest FW, as a lot of it h=will have to be rewritten anyway.

[1] https://github.com/fiduswriter/fiduswriter/blob/b297e46eb890569676ef395fa1db617677306912/document/static/js/es6_modules/editor/plugins/links.js

See also a few seconds of demo video here: https://www.youtube.com/watch?v=lPKEJ7vQDHc&feature=youtu.be

**Comment by johanneswilm** [comment]
Hey, I can see from thus weeks agenda that this currently being debugged. I am afraid that will be a waste of time before the underlying FW has been updates. Almost certainly the entire code needs to be written again as so much has changed since May, both with Niloofar's headline id code and most recently the upgrade to the latest prosemirror. I can help with the rewrite though.

**Comment by johanneswilm** [comment]
@sadeghiafshin @s6fikass Hey guys, I have here ported the anchor tag to be compatible with both Niloofar's code and the newest PM. It is very simple:

- add a new button to add anchors (no new icon for now)
- if the caret is inside an anchor mark, show the URL for that anchor in the URL bar
- scroll to the beginning of content marked with the anchor if someone opens the editor with the anchor hash in the URL.

https://github.com/fiduswriter/fiduswriter/tree/anchor-mark

It is very simple for now, but should cover the main usecase. I also tried adding an inline menu, similar to the one for links, but then I wasn't sure what extra info to add to that box. If you do add that, just follow how it's done for the link drop up.

I am sure you, @s6fikass, can continue from here and turn this into something that is both working with the new FW and fulfills your expectations. It is just one commit and I will not work any more on this until you let me know it should be merged.

**Comment by johanneswilm** [comment]
So, @s6fikass, if you are going to add a dropup, the best solution is probably to add it to the same link plugin. The link plugin takes care of changing and contents of the URLbar and does everything else concerning links/anchors. We should probably also add something to the link dialog so that one can link to these passages  as another type of internal link.

When I said that anchors function like comments, I really just meant conceptually that we have somewhere in the document to link them to, not that we should copy the code. The code for comments will need to be more complex because, among other things, for comments there is a period between first clicking on "new comment" and until the user has entered the comment text and the comment is made to be part of the document (unless the user cancels before that). For anchors there is no extra data that needs to be entered and it can all be done in just one operation, just like making text bold or italic.

**Comment by s6fikass** [comment]
@johanneswilm  
I get what you mean i will update the code to maintain what you mentioned, but when you are talking about adding it to the link plugin do you mean the one in here: 
https://github.com/fiduswriter/fiduswriter/tree/anchor-mark 
or is there another place to add it

**Comment by johanneswilm** [comment]
@s6fikass Yes, I mean the file that I added most thinks in that branch.This one: https://github.com/fiduswriter/fiduswriter/blob/anchor-mark/document/static/js/es6_modules/editor/plugins/links.js

I was thinking over the last few days that there may still be another point in having a drop-up like the one for links: That way we can give the user an easy way to remove the anchor. For links we didn't have anchors for a long time, and this was something some users complained about. See this drop up for a link and how it's handled.

![screenshot-localhost-8000 2017-08-06 20-59-26](https://user-images.githubusercontent.com/595512/29006133-2a1cc794-7aea-11e7-9e78-47bb8b41a6b7.png)

In the code that I briefly had that would add drop-ups both for links and for anchors (which I since deleted but which you should be able to add easily again ins links.js), there was some complexity for the case when the caret is in a place that is both part of a link and part of an anchor: In that case there would be two drop-ups, and then one needs to make sure that they are not covering oneanother.

**Comment by johanneswilm** [comment]
@s6fikass And yes, please just take over the anchor-mark branch. I just quickly threw together the things I best knew how to connect in that branch. If you continue with that branch, then I can merge it whenever you tell me it's ready.

**Comment by s6fikass** [comment]
Ok i will be taking over this branch and once i finished i would inform you but can you confirm the following:

1. the anchor and the internal links have the same Uri prefix would it be ok or use different uri.
2. the outlines menu is it still needed and if yes do we keep the remove buttons there.

**Comment by johanneswilm** [comment]
> the anchor and the internal links have the same Uri prefix would it be ok or use different uri.

I would say use the same. What's the point of using different ones? For the user it simply means that headlines and links automatically serve as anchors and additionally they can add their own anchors if need be. I think complicating this will just make the feature unusable. We have to remember that we are creating a tool for a number of journal editors and journal text writers who aren't computer experts. It will be challenging already explaining to many authors what anchors are. Making this any more complicated than absolutely necessary will just make them say no to the entire project.

 > the outlines menu is it still needed and if yes do we keep the remove buttons there.

I would say we should entirely remove the outlines menu. It's not really an outlines menu anyway, because it ignores all the headlines of the document and just focuses on the anchors and so it will just be confusing to the user. The information given in that menu (the anchor link) should now be available through the URL-change in the URL-bar and additionally could be added to a drop-up.

**Comment by johanneswilm** [comment]
Has been merged a while ago.
