### ISSUE TITLE
Configuration takes no effect

### ISSUE THREAD

**Issue by dalareo** [fiduswriter/fiduswriter#458]
No matter what options I set in configuration.py-default, when the server starts (manage.py init && manage.py runserver) fiduswriter.settings are always the same.
Is there any step I need to do in order to make fiduswriter.settings get the values from configuration.py?

**Comment by johanneswilm** [comment]
Not really, just renaming configuration.py-default to configuration.py should make these settings override the default options. 

Did you try runnign it without docker? Did it work then?

**Comment by dalareo** [comment]
With or without docker I get the same error after running "./manage.py init", I guess it has something to do with the configuration values not taking effect:

```
expecting file at (...) skipping...

```
after usermedia.0004
![screenshot-0](https://user-images.githubusercontent.com/919861/27837392-3adaa576-60e4-11e7-9d62-0437851213b7.jpg)

**Comment by johanneswilm** [comment]
The expected file warning is OK. For some reason it expects the file to be in all directories, but it works fine.

What platform are you trying to run this on?

**Comment by johanneswilm** [comment]
Also notice, that this is not just ordinary django. We mix django with tornado but bundle it all together so that the runserver command works similar to simple django for conveince of the user. But if you patch things or run other commands thna what is decribed in the Readme and wiki, you may very well run into issues. I see you are using python 3.6 -- so I guess you are not running this on Ubuntu 16.04 or diverging from the instructions in some other way?

**Comment by dalareo** [comment]
I am running Arch Linux. 
I got the warning when running inside Docker also, but if it is fine then there is another thing going wrong. I cannot test it without docker as long as I don't have a machine with Ubuntu 16.04.

**Comment by johanneswilm** [comment]
Could you test it with python 2? It should run with Python 3, but 2 is still the default in Ubuntu 16.04, so we run that on testing servers, etc. . If that is the issues, we can work on getting that to work.

So it is fully installing, but it is then not using the settings form the configuration.py file?

In that case it seems these lines are not working for you for some reason:

https://github.com/fiduswriter/fiduswriter/blob/develop/fiduswriter/settings.py#L336-L339

**Comment by dalareo** [comment]
Yes, the problem is that it takes values from 'fiduswriter/fiduswriter/settings.py' and not from 'configuration.py'.
As long as it is not creating a /data folder I guess It has something to do with this, because the 'configuration.py' file the program is reading must be placed there, isn't it?

**Comment by johanneswilm** [comment]
The django standard is that it reads form the settings.py file.  But we added the lines I linked to in that settings.py file so that it imports settings from the configuration.py file and lets those override anything defined in settings.py. It basically says "If there is a file with the name configuration.py in the folder above the one with the settings.py file in it, then use the settings from that file."

I don't know exactly how you have moved things around, but these lines will need to be adjusted if anything is completely different.

**Comment by johanneswilm** [comment]
@dalareo So you found a solution?

**Comment by dalareo** [comment]
I am using settings.py as configuration file

**Comment by johanneswilm** [comment]
Ok, you will then likely have merge problems if we change anything. But as long as you handle those manually, you should be fine.

**Comment by dalareo** [comment]
Solved using 'python:2.7' image as origin instead of 'ubuntu:16.04'
