### ISSUE TITLE
export to html special characters

### ISSUE THREAD

**Issue by jucajuca** [fiduswriter/fiduswriter#474]
Hi,

when I export a document to html some special characters are not exported correctly
for example:

Ertiö --->      ErtiÃ¶ 
Höffken ---> HÃ¶ffken

**Comment by johanneswilm** [comment]
Will take a look

**Comment by johanneswilm** [comment]
Hey @jucajuca . Actually it looks correct. The output is declared as HTML5, and the default encoding of that output is utf-8 [1]. Are you looking at the page in Firefox? In Firefox I also get it to show incorrectly using a different character encoding. This seems to be due to 5+ year old Firefox bugs [2][3] that the Firefox team either disagrees with or chooses not to do anything about for other reasons. I don't think we can do much about this.  Unfortunately, seems to be less relevant as a browser in recent years.

@jucajuca, please reopne if you have a suggestion.


[1] https://www.w3schools.com/html/html_charset.asp
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1071816
[3] https://bugzilla.mozilla.org/show_bug.cgi?id=815551
