### ISSUE TITLE
"Last change " updates by opening a document, its format is not correct. 

### ISSUE THREAD

**Issue by sadeghiafshin** [fiduswriter/fiduswriter#475]
please check the photo.
<img width="349" alt="screen shot 2017-08-02 at 10 03 31" src="https://user-images.githubusercontent.com/3121986/28863773-8b44f6e6-776a-11e7-8154-cc54584cfe79.png">

**Comment by sadeghiafshin** [comment]
I opened the document and the "last changed" updated to today

**Comment by johanneswilm** [comment]
What is wrong about the format?
It is true that the last updated is updated even with the smallest change.
Some such updates may happen without the user realizing it (such as merfing
of previous changes that weren't merge at last connect).

**Comment by sadeghiafshin** [comment]
I tested by opening three documents. I opened them and closed them and the date changed. By format it was the idea of Christoph, I guess he meant the m/d/y combination.

**Comment by johanneswilm** [comment]
The update can happen if a user abruptly loses server connection and them reconnects another day. In development this can happen if one shuts down the dev server while clients are connected. We could turn this off but we may then run into more problems when upgrading the server.

I have forgotten how the date presentation is calculated. I think it should either be the local format of the user or the ISO-format yyyy-mm-dd.

**Comment by sadeghiafshin** [comment]
Then a solution can be we change the "last changed" date when the content is changed. The history feature under developing can be used for this.

**Comment by johanneswilm** [comment]
I doubt it.

Let me try to explain the issue a bit more: The fidus writer fromat consists of a JSON structure. This structure is understood by the JavaScript in the cleint, but not the Python server. So what is happening is that every two minutes, the cleint sends a fully merged version of this JSON structure to the server, which then saves it. Also when disconnecting, the client sends a full copy of the JSON to the server for saving.

In-between these saves, the server receives individual diff updates to the document which it distributes to all connected clients.


In the case of an unplannned disconnection by the client, when the server receives no last update of the entire JSON structure before the client signs out, it will instead save the last received JSON structure + any subsequently received diffs. The next time a client connects to the sevrer, it will then receive the JSON structure + these last diffs. it will merge the diffs into the JSON and immediately send the full JSON to the server for saving. This is why the save time of the document is being updated, even though the user hasn't made any change right at that moment.

We could turn this immediate merging of changes off. The the update time would not be changed. But that would mena that we would have more documents with unmerged changes. In the case of a server upgrade to a new Fidus Writer version, we may then run into the problem that the old diffs no longer can be applied. We have put in place a specific upgrade script that should be run before upgrading to merge all the diffs, but it seems like noone is using it.

I don't think the history plugin can do much about it. Alos, it seems like a fairly minor problem. In regular use, when the server is running constantly, this should only happen if a user is on a train with a bad connection or the user closes his laptop without signing out, etc. I believe I have seen Google Docs with similar behaviour at least in the past.

**Comment by johanneswilm** [comment]
What could be done is that instead of showing the last saved time, we keep a timestamp with each incoming diff and then save the time of the last incoming and accepted diff. This would be totally possible, but it would require extra computing power on the server and i'm not sure it is justified to do this given that it is a fairly minor issue.

**Comment by sadeghiafshin** [comment]
I opened the document then I pushed the "back" button of browser to get back to the list of documents. Is that considered a disconnection to the server?

**Comment by johanneswilm** [comment]
If you click the back button, it should be considered an ordinary disconnect. So before unloading the page, it will save the full JSON with whatever changes you made. This shouldn't be a problem. The unplanned disconnect happens if someone for example disconnects from the network unexpectedly or the server is shut down without warning. The browser doesn't know it will disconnect from the document now, so it doesn't know it will update.

Another reason such an update can occur is if we upgrade FW to a new version: In FW 3.2 we added IDs to headlines. So if we upgraded a server from FW 3.1 to 3.2, we can either run the upgrade script immediately after updating, which will upgrade all documents on that server right then by adding IDs to all existing headlines. Alternatively, we can wait until a user opens the document. It will then immediately be upgraded from the FW 3.1 to the FW 3.2 format and saved. The saving will then also upgrade the "last changed" timestamp.

Btw, all this will only happen if the user has write access. If the user has no write access to the document, it will still be upgraded and diffs be merged, but only "locally" in the client. The server won't accept any changes to be saved from that user and the timestamp won't update either.
