### ISSUE TITLE
4th 5th level headings are not styled

### ISSUE THREAD

**Issue by jucajuca** [fiduswriter/fiduswriter#486]
Hi,

I noticed that the 4th 5th level headings are not styled in the editor. 
I tried to find the css for this but I couldn't find it.

Best!

**Comment by johanneswilm** [comment]
Thank you! Why document style are you using?

**Comment by jucajuca** [comment]
comfy elephant 🐘

where would be the relevant file?

**Comment by johanneswilm** [comment]
Well, it's inside a fixture file [1], which is not ideal, because it cannot be edited by hand easily. I would like us to have all the styles in a separate repository [2] and then automatically get them from there upon installation.

You can change the style locally through the admin interface [3].

[1] https://github.com/fiduswriter/fiduswriter/blob/develop/style/fixtures/initial_styles.json
[2] https://github.com/fiduswriter/styles
[3] http://localhost:8000/admin/style/documentstyle/1/change/
