### ISSUE TITLE
Cannot export as LaTeX

### ISSUE THREAD

**Issue by m-schmale** [fiduswriter/fiduswriter#717]
Hi,

Fidus Writer seems to work on my Raspberry Pi 3 B+. However, I get this message, when I try to export a document as LaTeX: "**Latex exporter is temporarily out of order.**" The export as HTML and EPUB works, but other methods fail.

I read about Fidus Writer in this blog post: https://www.fiduswriter.org/2018/06/18/running-fidus-writer-on-a-raspberry-pi/ … and I do not think that the Raspberry Pi is officially supported, but, other than share-latex, it should run on a Pi according to this post. So it is not a hardware limitation.

Browser:  Newest Firefox/Chrome/Edge

Does this mean that something with my installation went wrong?
Unfortunately, there is no output in the console. For this reason, I do not know where to look for errors.

Thanks again

Regards,
Mark

**Comment by johanneswilm** [comment]
Hey @m-schmale , what it means is that you are running the development version of Fidus Writer. This version is meant for development and at times certain features are not working because we are programming on them. If you want to use Fidus Writer for production use, please use the latest stable version (master branch).
I will keep this ticket open as we need to fix it before the next stable release.

**Comment by johanneswilm** [comment]
fixed in develop
