### ISSUE TITLE
equation numbers

### ISSUE THREAD

**Issue by sbitzer** [fiduswriter/fiduswriter#98]
I couldn't find a way of adding equation numbers. To be precise what is needed is something like this:

a = b + c        (1)

I couldn't get something like that with the image add button. Also, it would be preferable, if equations added via the image add button hadn't got the box around them as they are supposed to closely relate to the surrounding text.

**Comment by kbostroem** [comment]
The question remains unanswered, so I would like to push this thread again. I also urgently need to number my equations (NOT inline, of course!). Is there no way (yet) to do it in Fidus Writer?

**Comment by kbostroem** [comment]
To further pronounce the urgency of such a feature: Without the possibility to number equations, Fidus Writer, as beautiful as it already looks, is effectively useless for academic writing. Or has anyone seen a published scientific paper involving equations, and none of them is numbered?

**Comment by johanneswilm** [comment]
@kbostroem : Thanks for your feedback. Please remember that the academic disciplines are different and there are different requirements for each. There certainly are lots of disciplines and papers without inline numbered equations out there.

What is currently not possible is inline numbered equations, unless you create your own document stylesheet. 

Please not that we are a non-profit run in our own spare time. If you think this is an important feature and you think there is enough support for this in math departments, etc., you could try to help us find the funding to make this possible. Alternatively, if you know someone with programming skills, we are always happy to incorporate contributions.

What is possible is numbered block equations. Have you tried that?
 
![block-equation](https://cloud.githubusercontent.com/assets/595512/5691611/edc8abe4-98d0-11e4-8cf1-6c85925f276c.png)

To do those, click on the image symbol rather than the equation symbol.

**Comment by kbostroem** [comment]
Hi Johannes, thanks for your fast response! I really like the look and feel of Fidus Writer, and I was excited to finally see a tool that is SO close to what I was looking for for such a long time. Really great work and thanks for the non-profit efforts you put into this!
What I mean, and what the OP certainly also meant, was not a numbered INLINE formula, but rather a numbered DISPLAY formula. Something like this:
![bildschirmfoto 2015-01-10 um 22 39 29](https://cloud.githubusercontent.com/assets/7829808/5693368/973aaca2-9919-11e4-8e81-823846c997e3.png)
In LaTeX, an inline formula is created by $a=b$, and a (numbered) display formula is created by \begin{equation}a=b\end{equation}. The scientific domain where I'm working in (physics, neuroscience, theoretical biology, neural networks, movement science) is full of formulas of both types, and there is hardly one publication without numbered display equations. The workaround you suggest, with the  Figure environment, is not really a solution, for it looks like a numbered figure with a figure caption and not like a numbered equation. Readers would be confused and the manuscript would look unprofessional. Is it not possible to implement the equation environment into Fidus, just like you  implemented the figure environment?

**Comment by johanneswilm** [comment]
You can exchange the name "Figure" with other words such as "Table", etc. . We can also add a "Equation" to that list, if that means that it makes more sense to you.

As for more complex things: The academic publishing industry is a 10 Billion USD field. I find it a bit hard to believe that there is no money available at all to get a an editing environment and that therefore the four of us need to do this in our spare time. We have already spent two years development time on this. We may still decide to do it at some point of time because we need it ourselves, but until then, this is basically what we can offer. Alternatively, if you or someone else out there finds the time to do it, I'll be happy working to integrate your patches.

**Comment by kbostroem** [comment]
The academic publishing industry seems to be content with the situation as is. They won't spend any money if it's not paying out for them. Academics are struggling with office software that is not really suited to their needs, but somehow everybody manages to produce a manuscript that meets the criteria of their field of research. I was also wondering, why on earth there is no truly user-friendly LaTeX environment, or an alternative to LaTeX that is based on semantic editing and not on the WYSYWYG paradigm. Semantic editing is just so more natural and offers so many advantages, but people do not seem to have grasped it, maybe because they have been blinded for decades by Word & Co. On the other hand, the existing solutions for semantic editing like LaTeX and LyX, are too "nerdy" in that they are not user-friendly enough and look rather ugly. Fidus Writer is the first semantic editing solution that I have seen, which looks sexy and is user-friendly. 
I would really like to contribute, but I can't promise. I will look into the GitHub files and see if I get my head wrapped around it. In the meantime, could you consider implementing the equation environment anyway?

**Comment by johanneswilm** [comment]
equation as a separate numbering category is available in version 3.10.
